import localFont from "next/font/local";
import TopNav from "./TopBar/TopNav";
import "./globals.css";

const kepler = localFont({
 src :[
  {
    path:"../../public/Font/KeplerStd-BoldScnDisp.woff",
    weight:"200"
  },
  
 ],
 variable:'--font-kepler-std'
});
const bubbleGum = localFont({
  src: [
    {
      path: "../../public/Font/BubblegumSans-Regular.ttf",  // BubbleGum ka path
      weight: "400",
    },
  ],
  variable: "--font-bubblegum",
});

export const metadata = {
  title: "littlemumins",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="shortcut icon" href="/little.svg" type="image/svg+xml" />
      <link rel="icon" type="image/svg+xml" href="/HeyJini-icon.svg" sizes="any" />
      </head>
      <body className={`${bubbleGum.className} antialiased`}>
        <TopNav />
        {children}
      </body>
    </html>
  );
}